services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - postgres
    # Run a command against the development stage of the image
    command: yarn run start:dev
    ports:
      - 3000:3000

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  adminer:
    container_name: adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8010:8080
    depends_on:
      - postgres

volumes:
  postgres:
  redis:
    driver: local